### ISSUE TITLE
user is able to add negative values on edit page

### ISSUE THREAD

**Issue by cosmic-wavelet** [atulbansal4444/ExpenseTrackerApp#9]
user is able to add negative values on edit page
![Screenshot 2024-05-13 at 21-23-49 React App](https://github.com/atulbansal4444/ExpenseTrackerApp/assets/76049343/5944cf90-4198-4a1f-ae92-ba577739170c)

**Comment by atulbansal4444** [comment]
@cosmic-wavelet  Fixed as https://github.com/atulbansal4444/ExpenseTrackerApp/pull/10
Thanks!
